"""Regenerates docs/continuation/MODULE_MAP.md from the real import graph.

    python3 tooling/check/module_map.py
"""
import collections, json, os, re

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
CONFIG = json.load(open(os.path.join(os.path.dirname(__file__), "sections.json")))
SRC = os.path.join(REPO, CONFIG["sourceRoot"])
OUT = os.path.join(REPO, "docs", "continuation", "MODULE_MAP.md")
SPEC = re.compile(r'''(?:from\s+|import\s*\(\s*|^import\s+)["'](\.{1,2}/[^"']+)["']''', re.M)
HELPER = re.compile(r"^(?:export\s+)?(?:const|function)\s+(RESET|BOLD|DIM|paint)\b", re.M)
PURPOSE = {
    "text": "Escape codes, glyph sets, colour depth, visible width and clipping. Depends on nothing.",
    "platform": "Process and environment concerns: config paths and settings, network, endpoints, updates, doctor, i18n, currency.",
    "catalog": "The command registry every menu, key binding and guide reads.",
    "theme": "Palette roles and theme files; the only place colours are named.",
    "terminal": "Terminal I/O and layout: screens, scroll regions, viewport, output sinks, keys and wheel input.",
    "render": "Pure transcript renderers: markdown, sections, code, patch and test views, charts, banner, guide text.",
    "ui": "Interactive menus and full screens, and the fixed workspace frame.",
    "session": "Tabs, models, fallback, spend, history and exported sessions.",
    "commands": "Slash-command features built from the sections below them.",
}


def source_modules():
    for directory, _, files in os.walk(SRC):
        rel_dir = os.path.relpath(directory, SRC)
        if rel_dir.split(os.sep)[0] == "pty":
            continue
        for name in files:
            if re.search(r"\.tsx?$", name) and not re.search(r"\.test\.tsx?$", name):
                yield os.path.normpath(os.path.join(rel_dir, name)).replace(os.sep, "/")


def resolve(importer, specifier, known):
    base = os.path.normpath(os.path.join(os.path.dirname(importer), specifier)).replace(os.sep, "/")
    return next((c for c in (base, base + ".ts", base + ".tsx") if c in known), None)


def purpose(text):
    for line in text.splitlines():
        match = re.match(r"^\s*(?:/\*\*|\*)\s+([A-Z`].*)", line)
        if match:
            return match.group(1).strip().rstrip("*/").strip()[:110]
    return ""


def section(path):
    first = path.split("/")[0]
    return first if "/" in path and first in CONFIG["allowed"] else "root"


modules = sorted(source_modules())
known = set(modules)
texts = {m: open(os.path.join(SRC, m)).read() for m in modules}
fan_in = collections.Counter()
for m in modules:
    for spec in SPEC.findall(texts[m]):
        target = resolve(m, spec, known)
        if target:
            fan_in[target] += 1
helpers = collections.defaultdict(list)
for m in modules:
    for name in HELPER.findall(texts[m]):
        helpers[name].append(m)

lines = [
    "# Module map: `packages/archymedes-cli/src`",
    "",
    "Generated by `python3 tooling/check/module_map.py` from the import graph and",
    "`tooling/check/sections.json`. Do not edit by hand. The layering guard in `bun run recheck`",
    "enforces the import matrix below.",
    "",
    "## Sections",
    "",
    "Lower sections never import higher ones. Files at the root are entry points and may import anything.",
    "",
    "| Section | Purpose | May import |",
    "| --- | --- | --- |",
]
for name, allowed in CONFIG["allowed"].items():
    others = [a for a in allowed if a != name]
    lines.append(f"| `{name}/` | {PURPOSE.get(name, '')} | {', '.join(f'`{a}`' for a in others) or 'nothing'} |")
lines.append("| root | Entry points: the terminal CLI, headless and ACP front ends, the background job worker. | anything |")

for name in [*CONFIG["allowed"], "root"]:
    members = [m for m in modules if section(m) == name]
    lines += ["", f"## `{name}`" if name != "root" else "## root", "", "| Module | Lines | Imported by | Responsibility |", "| --- | ---: | ---: | --- |"]
    for m in members:
        count = sum(1 for _ in texts[m].splitlines())
        responsibility = purpose(texts[m]).replace("|", "\\|")
        lines.append(f"| `{m}` | {count} | {fan_in[m]} | {responsibility} |")

large = [(m, sum(1 for _ in texts[m].splitlines())) for m in modules]
lines += [
    "",
    "## Open findings",
    "",
    f"- **Large files (over 800 lines):** {', '.join(f'`{m}` ({n})' for m, n in large if n > 800) or 'none'}.",
    f"- **Duplicate escape helpers:** {'; '.join(f'`{k}` in ' + ', '.join(f'`{p}`' for p in v) for k, v in sorted(helpers.items()) if len(v) > 1) or 'none'}.",
    f"- **Modules with no source importer:** {', '.join(f'`{m}`' for m in modules if fan_in[m] == 0 and section(m) != 'root') or 'none'}.",
]
open(OUT, "w").write("\n".join(lines) + "\n")
print(f"wrote {os.path.relpath(OUT, REPO)}: {len(modules)} modules")
